#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

ynh_print_info "Declaring files to be backed up..."

#=================================================
# BACKUP THE COTURN CONFIGURATION
#=================================================

ynh_backup "/etc/turnserver.conf"

#=================================================
# BACKUP THE COTURN DATAPATH
#=================================================

ynh_backup "$data_dir"

#=================================================
# SPECIFIC BACKUP
#=================================================

ynh_backup "/var/log/$app"

ynh_backup "/etc/cron.d/$app"

ynh_backup "/etc/systemd/system/$app.service"

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
