#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STORE SETTINGS FROM MANIFEST
#=================================================

ynh_app_setting_set --key=no_sso --value=true

#=================================================
# CREATE A DH FILE
#=================================================
ynh_script_progression "Creating a dhparam file..."

# Make dhparam cert for Coturn if it doesn't exist
if [ ! -e /etc/ssl/private/dh2048.pem ]
then
    ynh_hide_warnings openssl dhparam -out /etc/ssl/private/dh2048.pem -outform PEM -dsaparam 2048
    chown root:ssl-cert /etc/ssl/private/dh2048.pem
    chmod 640 /etc/ssl/private/dh2048.pem
fi

#=================================================
# CREATE DEDICATED USER
#=================================================
ynh_script_progression "Configuring system user..."

# Create a system user
adduser turnserver ssl-cert

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression "Configuring $app's systemd service..."

mkdir -p /var/log/$app

# Create systemd service for turnserver
ynh_config_add --template="default.coturn" --destination="/etc/default/coturn"

# Create a dedicated systemd config
ynh_config_add_systemd

#=================================================
# SET COTURN CONFIG
#=================================================
ynh_script_progression "Configuring Coturn..."

# Find password for turnserver
turnserver_pwd=$(ynh_string_random --length=30)
ynh_app_setting_set --key=turnserver_pwd --value=$turnserver_pwd

coturn_config_path="/etc/turnserver.conf"

ynh_config_add --template="turnserver.conf" --destination="$coturn_config_path"

# Get public IP and set as external IP for coturn
# note: '|| true' is used to ignore the errors if we can't get the public ipv4 or ipv6
public_ip4="$(curl -s ip.yunohost.org)" || true
public_ip6="$(curl -s ipv6.yunohost.org)" || true

if ( [[ -n "$public_ip4" ]] && ynh_validate_ip --family=4 --ip_address="$public_ip4" || [[ -n "$public_ip6" ]] && ynh_validate_ip6 --ip_address="$public_ip6" )
then
    echo "external-ip=${public_ip4}/${public_ip6}" >> "$coturn_config_path"
fi

ynh_store_file_checksum "$coturn_config_path"

#=================================================
# ADD SCRIPT FOR COTURN CRON
#=================================================

# For any update do it in all files
cp -f ../sources/Coturn_config_rotate.sh $data_dir/
ynh_replace --match="__APP__" --replace=$app --file=$data_dir/Coturn_config_rotate.sh

chmod +x $data_dir/Coturn_config_rotate.sh

#=================================================
# SET COTURN CRON
#=================================================

ynh_config_add --template="cron_coturn" --destination="/etc/cron.d/$app"

#=================================================
# SETUP LOGROTATE
#=================================================
ynh_script_progression "Configuring log rotation..."

ynh_config_add_logrotate  "/var/log/$app"

#=================================================
# SECURE FILES AND DIRECTORIES
#=================================================

# Set permissions to app files
chown root: -R $data_dir
#REMOVEME? Assuming ynh_config_add_logrotate is called, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R turnserver:root /var/log/$app
chown turnserver:root /etc/turnserver.conf
setfacl -R -m user:turnserver:rwX  /var/log/$app

#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression "Integrating service in YunoHost..."

yunohost service add $app --description="Coturn TURN server" --log="/var/log/$app/$app.log" --needs_exposed_ports="$port_turnserver_tls"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

# Start a systemd service
ynh_systemctl --service=$app --action=restart

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Installation of Coturn completed"
