#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# LOAD SETTINGS
#=================================================
ynh_script_progression --message="Loading installation settings..." --weight=1

app=$YNH_APP_INSTANCE_NAME

domain=$(ynh_app_setting_get --app=$app --key=domain)
turnserver_tls_port=$(ynh_app_setting_get --app=$app --key=turnserver_tls_port)
turnserver_alt_tls_port=$(ynh_app_setting_get --app=$app --key=turnserver_alt_tls_port)

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE SERVICE INTEGRATION IN YUNOHOST
#=================================================
ynh_script_progression --message="Removing $app service integration..." --weight=1

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_exec_warn_less yunohost service status $app >/dev/null
then
	yunohost service remove $app
fi

#=================================================
# STOP AND REMOVE SERVICE
#=================================================
ynh_script_progression --message="Stopping and removing the systemd service..." --weight=1

# Remove the dedicated systemd config
ynh_remove_systemd_config

#=================================================
# REMOVE DEPENDENCIES
#=================================================
ynh_script_progression --message="Removing dependencies..." --weight=1

# Remove metapackage and its dependencies
ynh_remove_app_dependencies

#=================================================
# REMOVE APP MAIN DIR
#=================================================
ynh_script_progression --message="Removing Coturn configuration file..." --weight=2

ynh_secure_remove --file="/etc/turnserver.conf"
mv /etc/turnserver.conf.orig /etc/turnserver.conf

#=================================================
# REMOVE LOGROTATE CONFIGURATION
#=================================================
ynh_script_progression --message="Removing logrotate configuration..." --weight=1

# Remove the app-specific logrotate config
ynh_remove_logrotate

#=================================================
# REMOVE SCRIPT
#=================================================

# Remove coturn/Coturn_config_rotate.sh 
ynh_secure_remove --file="/home/yunohost.app/$app"

#=================================================
# REMOVE CRON JOB
#=================================================

# Remove a cron file
ynh_secure_remove --file=/etc/cron.d/$app

# Remove the log files
ynh_secure_remove --file=/var/log/$app

# Remove the sqlitedb file
#ynh_secure_remove --file=/var/lib/turn

#=================================================
# CLOSE PORTS
#=================================================

if yunohost firewall list | grep -q "\- $turnserver_tls_port$"
then
    ynh_script_progression --message="Closing port $turnserver_tls_port..." --weight=1
    ynh_exec_warn_less yunohost firewall disallow Both $turnserver_tls_port 
fi

if yunohost firewall list | grep -q "\- $turnserver_alt_tls_port$"
then
    ynh_script_progression --message="Closing port $turnserver_alt_tls_port..." --weight=1
    ynh_exec_warn_less yunohost firewall disallow Both $turnserver_alt_tls_port
fi

#=================================================
# GENERIC FINALIZATION
#=================================================
# REMOVE DEDICATED USER
#=================================================
ynh_script_progression --message="Removing the dedicated system user..." --weight=1

# Delete a system user
deluser turnserver ssl-cert
ynh_system_user_delete --username=turnserver

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed" --last
