#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STANDARD REMOVE
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

if ynh_hide_warnings yunohost service status $app >/dev/null; then
	yunohost service remove $app
fi

ynh_config_remove_systemd

ynh_safe_rm "/etc/turnserver.conf"

ynh_config_remove_logrotate

ynh_safe_rm /etc/cron.d/$app

#=================================================
# REMOVE DEDICATED USER
#=================================================
ynh_script_progression "Removing the dedicated system user..."

deluser turnserver ssl-cert

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
