#!/bin/bash

source /usr/share/yunohost/helpers

#=================================================
# RESTORE COTURN CONFIGURATION
#=================================================
ynh_script_progression "Restoring Coturn configuration..."

ynh_restore "/etc/turnserver.conf"

#=================================================
# RESTORE THE COTURN DATAPATH
#=================================================
ynh_script_progression "Restoring the data directory..."

ynh_restore "$data_dir"

#=================================================
# RESTORE LOG
#=================================================

ynh_restore "/var/log/$app"

#=================================================
# RECREATE THE DEDICATED USER
#=================================================
ynh_script_progression "Recreating the dedicated system user..."

# Create the dedicated user (if not existing)
adduser turnserver ssl-cert

#=================================================
# RECREATE A DH FILE
#=================================================
ynh_script_progression "Creating a dhparam file..."

# Make dhparam cert for Coturn if it doesn't exist
if [ ! -e /etc/ssl/private/dh2048.pem ]
then
    ynh_hide_warnings openssl dhparam -out /etc/ssl/private/dh2048.pem -outform PEM -dsaparam 2048
    chown root:ssl-cert /etc/ssl/private/dh2048.pem
    chmod 640 /etc/ssl/private/dh2048.pem
fi

#=================================================
# RESTORE USER RIGHTS
#=================================================

# Restore permissions on app files
# Set permissions to app files
chown root: -R $data_dir
chown -R turnserver:root /var/log/$app
chown turnserver:root /etc/turnserver.conf
setfacl -R -m user:turnserver:rwX  /var/log/$app

#=================================================
# RESTORE SYSTEMD
#=================================================
ynh_script_progression "Restoring $app's systemd service..."

ynh_restore "/etc/systemd/system/$app.service"
systemctl enable $app.service --quiet

yunohost service add $app --description="Coturn TURN server" --log="/var/log/$app/$app.log" --needs_exposed_ports="$port_turnserver_tls"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action=start

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Restoration completed for $app"
