#!/bin/bash


source /usr/share/yunohost/helpers

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action=stop

#=================================================
# CREATE DEDICATED USER
#=================================================
ynh_script_progression "Making sure dedicated system user exists..."

adduser turnserver ssl-cert

#=================================================
# SETUP SYSTEMD
#=================================================
ynh_script_progression "Configuring $app's systemd service..."

mkdir -p /var/log/$app

ynh_config_add --template="default.coturn" --destination="/etc/default/coturn"

ynh_config_add_systemd

#=================================================
# SET COTURN CONFIG
#=================================================
ynh_script_progression "Configuring $app..."

ynh_config_add --template="turnserver.conf" --destination="/etc/turnserver.conf"

# Get public IP and set as external IP for coturn
# note: '|| true' is used to ignore the errors if we can't get the public ipv4 or ipv6
public_ip4="$(curl -s https://ip.yunohost.org/)" || true
public_ip6="$(curl -s https://ip6.yunohost.org/)" || true

if ( [[ -n "$public_ip4" ]] && ynh_validate_ip --family=4 --ip_address="$public_ip4" || [[ -n "$public_ip6" ]] && ynh_validate_ip --family=6 --ip_address="$public_ip6" )
then
    echo "external-ip=${public_ip4}/${public_ip6}" >> "/etc/turnserver.conf"
fi

ynh_store_file_checksum "/etc/turnserver.conf"

#=================================================
# ADD SCRIPT FOR COTURN CRON
#=================================================

cp -f ../sources/Coturn_config_rotate.sh $data_dir/
ynh_replace --match="__APP__" --replace=$app --file=$data_dir/Coturn_config_rotate.sh

chmod +x $data_dir/Coturn_config_rotate.sh

#=================================================
# SET COTURN CRON
#=================================================

ynh_config_add --template="cron_coturn" --destination="/etc/cron.d/$app"

#=================================================
# MIGRATION 3 : USE STANDARD ACCESS FOR CERTIFCATE
#=================================================

# Fix issue about certificates access
# if [ ! $(grep "ssl-cert:x:[0-9]*:.*$app" /etc/group) ]
# then
#     ynh_script_progression "Use standard access for certificate..."
#     adduser turnserver ssl-cert
# fi

#=================================================
# SETUP LOGROTATE
#=================================================
ynh_script_progression "Configuring log rotation..."

ynh_config_add_logrotate

#=================================================
# SECURE FILES AND DIRECTORIES
#=================================================

chown root: -R $data_dir
chown turnserver:root /etc/turnserver.conf
setfacl -R -m user:turnserver:rwX  /var/log/$app

#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression "Integrating service in YunoHost..."

yunohost service add $app --description="Coturn TURN server" --log="/var/log/$app/$app.log" --needs_exposed_ports="$port_turnserver_tls"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action=restart

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of Coturn completed"
